name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build
      run: go build -v .
    
    - name: Build for different platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o timeout-mcp-linux-amd64 .
        GOOS=darwin GOARCH=amd64 go build -o timeout-mcp-darwin-amd64 .
        GOOS=windows GOARCH=amd64 go build -o timeout-mcp-windows-amd64.exe .
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          timeout-mcp-linux-amd64
          timeout-mcp-darwin-amd64
          timeout-mcp-windows-amd64.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          timeout-mcp-*
